{{- if and .Values.cnpg.enabled .Values.cnpg.backup.enabled }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "sharkey.cnpgBackupStoreName" . }}
  labels:
    {{- include "sharkey.labels" . | nindent 4 }}
spec:
  configuration:
    destinationPath: {{ .Values.cnpg.backup.s3Credentials.destinationPath | quote }}
    {{- if .Values.cnpg.backup.s3Credentials.endpointUrl }}
    endpointURL: {{ .Values.cnpg.backup.s3Credentials.endpointUrl | quote }}
    {{- end }}
    s3Credentials:
      accessKeyId:
        name: {{ .Values.cnpg.backup.s3Credentials.accessKeyId.name | quote }}
        key: {{ .Values.cnpg.backup.s3Credentials.accessKeyId.key | quote }}
      secretAccessKey:
        name: {{ .Values.cnpg.backup.s3Credentials.secretAccessKey.name | quote }}
        key: {{ .Values.cnpg.backup.s3Credentials.secretAccessKey.key | quote }}
    wal:
      compression: gzip
  retentionPolicy: {{ .Values.cnpg.backup.retentionPolicy | quote }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "sharkey.cnpgClusterName" . }}-backup
  labels:
    {{- include "sharkey.labels" . | nindent 4 }}
spec:
  cluster:
    name: {{ include "sharkey.cnpgClusterName" . }}
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: {{ .Values.cnpg.backup.schedule | quote }}
  backupOwnerReference: self
{{- end }}
