{{- if and .Values.cnpg.enabled .Values.cnpg.import.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sharkey.cnpgClusterName" . }}-source-credentials
  labels:
    {{- include "sharkey.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.import.sourceUser | quote }}
  password: {{ .Values.cnpg.import.sourcePassword | quote }}
{{- end }}
