apiVersion: v1
kind: Service
metadata:
  name: {{ include "sharkey.fullname" . }}
  labels:
    {{- include "sharkey.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sharkey.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sharkey.selectorLabels" . | nindent 4 }}
